# Generated by Django 5.1.5 on 2025-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition',
            name='remedy_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
