# Generated by Django 5.1.5 on 2025-05-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_skincondition_remedy_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skincondition',
            name='remedy_1',
        ),
    ]
