# Generated by Django 5.1.5 on 2025-05-16 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_remove_skincondition_remedy_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skincondition',
            name='remedies',
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('directions', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('skin_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_set', to='predictor.skincondition')),
            ],
        ),
    ]
