# Generated by Django 5.1.5 on 2025-06-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_skincondition_remedies_remedy'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='remedy_images/'),
        ),
    ]
