# Generated by Django 5.1.5 on 2025-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_remedy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCondition_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=255)),
                ('main_card_image', models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/')),
                ('basics_title', models.CharField(max_length=200)),
                ('basics_summary', models.TextField()),
                ('basics_content', models.TextField()),
                ('basics_image', models.ImageField(blank=True, null=True, upload_to='skin_conditions/basics_images/')),
                ('causes_title', models.CharField(max_length=200)),
                ('causes_summary', models.TextField()),
                ('causes_intro', models.TextField(blank=True)),
                ('causes_details', models.JSONField(blank=True, null=True)),
                ('causes_image', models.ImageField(blank=True, null=True, upload_to='skin_conditions/causes_images/')),
                ('treatments_title', models.CharField(max_length=200)),
                ('treatments_summary', models.TextField()),
                ('treatments_details', models.JSONField(blank=True, null=True)),
                ('treatments_image', models.ImageField(blank=True, null=True, upload_to='skin_conditions/prevention_images/')),
            ],
        ),
    ]
