# Generated by Django 5.1.5 on 2025-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_skincondition_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/prevention_images/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_lifestyle',
            field=models.JSONField(blank=True, help_text="Enter as JSON list: ['item1', 'item2', ...]", null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_skincare',
            field=models.JSONField(blank=True, help_text="Enter as JSON list: ['item1', 'item2', ...]", null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='basics_content',
            field=models.TextField(help_text='Enter detailed content, including HTML tags like <ul>, <li>, <strong> etc.'),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='causes_details',
            field=models.JSONField(blank=True, help_text="Enter as JSON: [{'heading': '...', 'description': '...'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='treatments_details',
            field=models.JSONField(blank=True, help_text="Enter as JSON: [{'heading': '...', 'description': '...'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='treatments_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/treatments_images/'),
        ),
    ]
