# Generated by Django 5.1.5 on 2025-07-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_skincondition_page_prevention_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition_page',
            name='basics_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/basics/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='causes_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/causes/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='treatments_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/treatments/'),
        ),
    ]
