# Generated by Django 5.1.5 on 2025-07-04 08:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_skincondition_page_basics_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincondition_page',
            name='basics_content',
            field=models.TextField(help_text='HTML content with <ul>, <li>, <strong> etc.'),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='causes_details',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="JSON format: [{'heading': '...', 'description': '...', 'icon': 'fas fa-icon-name'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='prevention_lifestyle',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="JSON format: [{'text': '...', 'icon': 'fas fa-icon-name'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='prevention_skincare',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="JSON format: [{'text': '...', 'icon': 'fas fa-icon-name'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='skincondition_page',
            name='treatments_details',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="JSON format: [{'heading': '...', 'description': '...', 'icon': 'fas fa-icon-name'}, ...]", null=True),
        ),
    ]
