# Generated by Django 5.1.5 on 2025-07-05 05:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_alter_skincondition_page_basics_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition_page',
            name='doctor_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/doctor/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='doctor_details',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="JSON format: [{'point': '...', 'icon': 'fas fa-icon-name'}, ...]", null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/doctor_images/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='doctor_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='doctor_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='symptoms_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/card_images/symptoms/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='symptoms_content',
            field=models.TextField(blank=True, help_text='HTML content describing symptoms, e.g., using <ul>, <li>, <strong>, etc. Can also be a general paragraph.', null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='symptoms_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/symptoms_images/'),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='symptoms_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincondition_page',
            name='symptoms_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
