# Generated by Django 5.1.5 on 2025-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_skincondition_page_doctor_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
