# Generated by Django 5.1.5 on 2025-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_remove_skincondition_page_prevention_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition_page',
            name='prevention_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_conditions/prevention_images/'),
        ),
    ]
