# Generated by Django 5.1.5 on 2025-07-07 18:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Name of the person submitting the review.', max_length=100)),
                ('rating', models.IntegerField(help_text='Rating given by the user (1 to 5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text='The detailed text of the review.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who submitted the review (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
